### ISSUE TITLE
Issues encoding and parsing an image using the NistFile interface

### ISSUE THREAD

**Issue by CadeKritsch** [ivosh/node-nist#26]
I am trying to encode a Type 10 Face image in my nist file with utf-8, but when using the syntax used in the node-nist codebase, the image gets corrupted and nist viewers cannot view this utf-8 encoding.  Similarly, a base64 encoding causes some issues because it is not supported by the NistFile interface.  

This is how I am downloading and reading the image:

const image = await this.downloadImage(user.picture.thumbnail);
const image: string = await fs.promises.readFile('t10-1.jpg','utf-8');

And this is how I am encoding the image into a buffer in the type 10 field:

999: Buffer.from(image, 'utf-8')

Is it possible to encode image data in the Type 10 field, and if so how?  Thank you for your time and help!

**Comment by ivosh** [comment]
Hi @CadeKritsch, first thank you for using the project.

Looking at the NodeJS documentation for [fs.promises.readFile](https://nodejs.org/api/fs.html#fspromisesreadfilepath-options) I see that: "If no encoding is specified (using `options.encoding`), the data is returned as a `Buffer`. Otherwise, the data will be a string."

The image data shall be binary, not a string.
Therefore I'd remove all `utf-8` options from your code dealing with the binary image data.
Have also look how the fingerprint binary data is read here:
https://github.com/ivosh/node-nist/blob/master/src/nistEncode.test.ts#L20
and then used here:
https://github.com/ivosh/node-nist/blob/master/src/nistEncode.test.ts#L520

If this helped to resolve your issue, I'd be very glad for a Pull Request from you enhancing the documentation of `node-nist`.

**Comment by CadeKritsch** [comment]
When I use the same process listed in those links, this is the error I receive when trying to open the resulting nist in a nist viewer:
![Capture](https://github.com/ivosh/node-nist/assets/73767994/dd1cb2ea-8405-46d1-9d1a-12f23bf0d779)
It seems like something is getting corrupted in the encoding.  The only difference between my process and the process used in the encoding test is that I am trying to encode a png, whereas the tests encode a wsq image.

**Comment by ivosh** [comment]
@CadeKritsch Understood. Are you setting the correct image compression algorithm in field 10.011 (CGA)?
If you can provide a reproducible test case, including all the input data, I will try to troubleshoot your issue with another NIST viewer.

**Comment by ivosh** [comment]
Almost one year has passed and no response from the submitter.
